/** @file
  Processor containers for the Apple T6002 family.

  Generated by Tools/add-soc.py from the device tree for
  Apple Mac Studio (M1 Ultra, 2022).

  Covers: t6002

  UNVERIFIED. Every address, core count and window below is what the device
  tree states; none of it has been read off this silicon by us, and no machine
  in this family has been booted. Treat a successful build as evidence that the
  package is self-consistent and nothing more.

  A separate SSDT rather than part of a board DSDT, because the CPU tree is a
  property of the die and the DSDT is a property of the board. Keeping it here
  is what lets one board package -- J414sBoardPkg, GenericBoardPkg -- serve
  machines built on different silicon.

  20 core(s) in 6 cluster(s) across 2 die(s).

  Scope (\_SB) is opened by the DSDT; this only adds to it.

  SPDX-License-Identifier: BSD-2-Clause-Patent OR MIT
**/

DefinitionBlock ("Cpus.aml", "SSDT", 0x02, "Apple", "T6002CPU", 0x6002) {
    Scope (\_SB) {
    Device (DIE0) {
        Name (_HID, "ACPI0010")
        Name (_UID, 0)

        // 2 efficiency core(s), device-tree cluster 0.
        Device (CL00) {
            Name (_HID, "ACPI0010")
            Name (_UID, 1)

            Device (C000) {
                Name (_HID, "ACPI0007")
                Name (_UID, 0)
                Name (_STR, Unicode ("Apple M1 Ultra Efficiency Core 0"))
                Name (_DDN, "Apple M1 Ultra Efficiency Core 0")
                Method (_STA) { Return (0xF) }
            }

            Device (C001) {
                Name (_HID, "ACPI0007")
                Name (_UID, 1)
                Name (_STR, Unicode ("Apple M1 Ultra Efficiency Core 1"))
                Name (_DDN, "Apple M1 Ultra Efficiency Core 1")
                Method (_STA) { Return (0xF) }
            }
        }

        // 4 performance core(s), device-tree cluster 1.
        Device (CL01) {
            Name (_HID, "ACPI0010")
            Name (_UID, 2)

            Device (C002) {
                Name (_HID, "ACPI0007")
                Name (_UID, 2)
                Name (_STR, Unicode ("Apple M1 Ultra Performance Core 0"))
                Name (_DDN, "Apple M1 Ultra Performance Core 0")
                Method (_STA) { Return (0xF) }
            }

            Device (C003) {
                Name (_HID, "ACPI0007")
                Name (_UID, 3)
                Name (_STR, Unicode ("Apple M1 Ultra Performance Core 1"))
                Name (_DDN, "Apple M1 Ultra Performance Core 1")
                Method (_STA) { Return (0xF) }
            }

            Device (C004) {
                Name (_HID, "ACPI0007")
                Name (_UID, 4)
                Name (_STR, Unicode ("Apple M1 Ultra Performance Core 2"))
                Name (_DDN, "Apple M1 Ultra Performance Core 2")
                Method (_STA) { Return (0xF) }
            }

            Device (C005) {
                Name (_HID, "ACPI0007")
                Name (_UID, 5)
                Name (_STR, Unicode ("Apple M1 Ultra Performance Core 3"))
                Name (_DDN, "Apple M1 Ultra Performance Core 3")
                Method (_STA) { Return (0xF) }
            }
        }

        // 4 performance core(s), device-tree cluster 2.
        Device (CL02) {
            Name (_HID, "ACPI0010")
            Name (_UID, 3)

            Device (C006) {
                Name (_HID, "ACPI0007")
                Name (_UID, 6)
                Name (_STR, Unicode ("Apple M1 Ultra Performance Core 0"))
                Name (_DDN, "Apple M1 Ultra Performance Core 0")
                Method (_STA) { Return (0xF) }
            }

            Device (C007) {
                Name (_HID, "ACPI0007")
                Name (_UID, 7)
                Name (_STR, Unicode ("Apple M1 Ultra Performance Core 1"))
                Name (_DDN, "Apple M1 Ultra Performance Core 1")
                Method (_STA) { Return (0xF) }
            }

            Device (C008) {
                Name (_HID, "ACPI0007")
                Name (_UID, 8)
                Name (_STR, Unicode ("Apple M1 Ultra Performance Core 2"))
                Name (_DDN, "Apple M1 Ultra Performance Core 2")
                Method (_STA) { Return (0xF) }
            }

            Device (C009) {
                Name (_HID, "ACPI0007")
                Name (_UID, 9)
                Name (_STR, Unicode ("Apple M1 Ultra Performance Core 3"))
                Name (_DDN, "Apple M1 Ultra Performance Core 3")
                Method (_STA) { Return (0xF) }
            }
        }
    }
    Device (DIE1) {
        Name (_HID, "ACPI0010")
        Name (_UID, 1)

        // 2 efficiency core(s), device-tree cluster 8.
        Device (CL08) {
            Name (_HID, "ACPI0010")
            Name (_UID, 9)

            Device (C010) {
                Name (_HID, "ACPI0007")
                Name (_UID, 10)
                Name (_STR, Unicode ("Apple M1 Ultra Efficiency Core 0"))
                Name (_DDN, "Apple M1 Ultra Efficiency Core 0")
                Method (_STA) { Return (0xF) }
            }

            Device (C011) {
                Name (_HID, "ACPI0007")
                Name (_UID, 11)
                Name (_STR, Unicode ("Apple M1 Ultra Efficiency Core 1"))
                Name (_DDN, "Apple M1 Ultra Efficiency Core 1")
                Method (_STA) { Return (0xF) }
            }
        }

        // 4 performance core(s), device-tree cluster 9.
        Device (CL09) {
            Name (_HID, "ACPI0010")
            Name (_UID, 10)

            Device (C012) {
                Name (_HID, "ACPI0007")
                Name (_UID, 12)
                Name (_STR, Unicode ("Apple M1 Ultra Performance Core 0"))
                Name (_DDN, "Apple M1 Ultra Performance Core 0")
                Method (_STA) { Return (0xF) }
            }

            Device (C013) {
                Name (_HID, "ACPI0007")
                Name (_UID, 13)
                Name (_STR, Unicode ("Apple M1 Ultra Performance Core 1"))
                Name (_DDN, "Apple M1 Ultra Performance Core 1")
                Method (_STA) { Return (0xF) }
            }

            Device (C014) {
                Name (_HID, "ACPI0007")
                Name (_UID, 14)
                Name (_STR, Unicode ("Apple M1 Ultra Performance Core 2"))
                Name (_DDN, "Apple M1 Ultra Performance Core 2")
                Method (_STA) { Return (0xF) }
            }

            Device (C015) {
                Name (_HID, "ACPI0007")
                Name (_UID, 15)
                Name (_STR, Unicode ("Apple M1 Ultra Performance Core 3"))
                Name (_DDN, "Apple M1 Ultra Performance Core 3")
                Method (_STA) { Return (0xF) }
            }
        }

        // 4 performance core(s), device-tree cluster 10.
        Device (CL10) {
            Name (_HID, "ACPI0010")
            Name (_UID, 11)

            Device (C016) {
                Name (_HID, "ACPI0007")
                Name (_UID, 16)
                Name (_STR, Unicode ("Apple M1 Ultra Performance Core 0"))
                Name (_DDN, "Apple M1 Ultra Performance Core 0")
                Method (_STA) { Return (0xF) }
            }

            Device (C017) {
                Name (_HID, "ACPI0007")
                Name (_UID, 17)
                Name (_STR, Unicode ("Apple M1 Ultra Performance Core 1"))
                Name (_DDN, "Apple M1 Ultra Performance Core 1")
                Method (_STA) { Return (0xF) }
            }

            Device (C018) {
                Name (_HID, "ACPI0007")
                Name (_UID, 18)
                Name (_STR, Unicode ("Apple M1 Ultra Performance Core 2"))
                Name (_DDN, "Apple M1 Ultra Performance Core 2")
                Method (_STA) { Return (0xF) }
            }

            Device (C019) {
                Name (_HID, "ACPI0007")
                Name (_UID, 19)
                Name (_STR, Unicode ("Apple M1 Ultra Performance Core 3"))
                Name (_DDN, "Apple M1 Ultra Performance Core 3")
                Method (_STA) { Return (0xF) }
            }
        }
    }
    }
}
