/** @file
  CPU topology for the Apple T6002 family.

  Generated by Tools/add-soc.py from the device tree for
  Apple Mac Studio (M1 Ultra, 2022).

  Covers: t6002

  UNVERIFIED. Every address, core count and window below is what the device
  tree states; none of it has been read off this silicon by us, and no machine
  in this family has been booted. Treat a successful build as evidence that the
  package is self-consistent and nothing more.

  THE CORE COUNT IS THE DIE, NOT THE MACHINE

  Apple bins these parts. The device tree describes the die as fabricated, and a
  given machine may have fewer cores fused on -- an M2 Pro die carries 12 and
  ships as 10 or 12, an M4 die carries 10 and ships as 8 or 10. Publishing a
  GICC for a core that is not there is not harmless: Windows issues PSCI CPU_ON
  for every enabled entry, and a truthful failure is answered with SYSTEM_RESET.

  AcpiPlatformDxe trims the MADT to the CPUs the live ADT reports before
  installing it, which is what makes a die-sized table safe here. The counts
  below are the ceiling that sizes the table.

  EFFICIENCY CLASS

  ACPI 6.3 defines a LOWER Processor Power Efficiency Class as MORE efficient,
  so E-cores are 0 and P-cores 1. That is what T6020J414sTopology.h does and
  what is emitted here. T8142J813Topology.h emits the opposite and documents
  why; do not copy it.

  SPDX-License-Identifier: BSD-2-Clause-Patent OR MIT
**/

#ifndef T6002_TOPOLOGY_H_
#define T6002_TOPOLOGY_H_

#define T6002_CPU_COUNT       20
#define T6002_CLUSTER_COUNT    6

#define T6002_CLUSTER0_CORE_COUNT    2   // E-cores
#define T6002_CLUSTER0_UID_BASE      0
#define T6002_CLUSTER0_L2_SIZE    0x00400000
#define T6002_CLUSTER0_EFFICIENCY    0

#define T6002_CLUSTER1_CORE_COUNT    4   // P-cores
#define T6002_CLUSTER1_UID_BASE      2
#define T6002_CLUSTER1_L2_SIZE    0x00C00000
#define T6002_CLUSTER1_EFFICIENCY    1

#define T6002_CLUSTER2_CORE_COUNT    4   // P-cores
#define T6002_CLUSTER2_UID_BASE      6
#define T6002_CLUSTER2_L2_SIZE    0x00C00000
#define T6002_CLUSTER2_EFFICIENCY    1

#define T6002_CLUSTER3_CORE_COUNT    2   // E-cores
#define T6002_CLUSTER3_UID_BASE     10
#define T6002_CLUSTER3_L2_SIZE    0x00400000
#define T6002_CLUSTER3_EFFICIENCY    0

#define T6002_CLUSTER4_CORE_COUNT    4   // P-cores
#define T6002_CLUSTER4_UID_BASE     12
#define T6002_CLUSTER4_L2_SIZE    0x00C00000
#define T6002_CLUSTER4_EFFICIENCY    1

#define T6002_CLUSTER5_CORE_COUNT    4   // P-cores
#define T6002_CLUSTER5_UID_BASE     16
#define T6002_CLUSTER5_L2_SIZE    0x00C00000
#define T6002_CLUSTER5_EFFICIENCY    1
//
// The core the firmware boots on must be the MADT's first GICC entry
// (ACPI 6.3 section 5.2.12.14). UID 0 is correct for every SoC we have
// measured except T8142, where m1n1 comes up on a P-core. UNVERIFIED here.
//
#define T6002_BOOT_CPU_UID 0

//
// Architected timer GSIVs, kept in step with T6002FamilyPkg.dsc.inc. Arbitrary:
// the timers are per-CPU FIQs on this silicon, not GIC PPIs.
//
#define T6002_GTDT_SECURE_EL1_GSIV    19
#define T6002_GTDT_NONSECURE_EL1_GSIV 17
#define T6002_GTDT_VIRTUAL_EL1_GSIV   18
#define T6002_GTDT_NONSECURE_EL2_GSIV 20

//
// Interrupt controller base, from the device tree. The geometry that goes with
// it -- IRQ counts, register strides, capability offsets -- is NOT in any
// device tree; Linux and m1n1 both read it off the controller at runtime. See
// CSRT.aslc.
//
#define T6002_AIC_BASE 0x000000028E100000ULL
#define T6002_AIC_SIZE 0x000000000000C000ULL

#endif /* T6002_TOPOLOGY_H_ */
