#!/usr/bin/env python3
# Copyright (c) 2026 Aurora Silicon

"""Compile and run the host-side MADT trimming regression test.

This wraps Tests/test_madt_adt_trim.c -- a standalone, EDK2-free C program that
exercises the exact table surgery
(Silicon/Apple/AppleSiliconPkg/Include/Drivers/NtasiMadtTrim.h) compiled into
AcpiPlatformDxe -- so it runs through the same `python3 -m unittest` entry point
as the rest of Tests/, with no EDK2 build, no ADT, and no hardware.

The SoC family packages generated by Tools/add-soc.py size their MADT to the
die, because the die is what Asahi's device tree describes. Apple bins these
parts, so a machine can have fewer cores. Publishing a GICC for a core that is
not there makes Windows issue PSCI CPU_ON for it and answer the failure with
SYSTEM_RESET, which ends the boot -- the trim is what makes a die-sized table
safe to generate.

The case that matters is the sparse one: a 10-core M2 Pro is not the first ten
of the die's twelve. T6020J414sTopology.h records that slots 7 and 11 are the
absent ones, so dropping by count rather than by identity would keep exactly the
wrong two.
"""

from __future__ import annotations

import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path


REPO = Path(__file__).resolve().parents[1]
SOURCE = REPO / "Tests" / "test_madt_adt_trim.c"
TRIM_HEADER = (
    REPO
    / "Silicon"
    / "Apple"
    / "AppleSiliconPkg"
    / "Include"
    / "Drivers"
    / "NtasiMadtTrim.h"
)


def _find_host_cc() -> str:
    for candidate in ("cc", "clang", "gcc"):
        path = shutil.which(candidate)
        if path:
            return path
    raise unittest.SkipTest("no host C compiler (cc/clang/gcc) found on PATH")


class TestMadtAdtTrim(unittest.TestCase):
    def test_source_files_present(self) -> None:
        self.assertTrue(SOURCE.is_file(), f"missing {SOURCE}")
        self.assertTrue(TRIM_HEADER.is_file(), f"missing {TRIM_HEADER}")

    def test_driver_uses_the_shared_header(self) -> None:
        """The driver must call the tested code, not its own copy of it."""
        driver = (
            REPO
            / "Silicon/Apple/AppleSiliconPkg/Drivers/AcpiPlatformDxe/AcpiPlatform.c"
        ).read_text(encoding="utf-8")
        self.assertIn("Drivers/NtasiMadtTrim.h", driver)
        self.assertIn("NtasiMadtTrim (", driver)

    def test_host_build_and_run_passes(self) -> None:
        compiler = _find_host_cc()
        with tempfile.TemporaryDirectory() as tmp:
            binary = Path(tmp) / "test_madt_adt_trim"
            compiled = subprocess.run(
                [compiler, "-std=c99", "-Wall", "-Wextra", "-Werror",
                 "-o", str(binary), str(SOURCE)],
                cwd=REPO,
                capture_output=True,
                text=True,
            )
            self.assertEqual(
                compiled.returncode,
                0,
                f"host compile failed:\nstdout={compiled.stdout}\nstderr={compiled.stderr}",
            )

            run = subprocess.run([str(binary)], capture_output=True, text=True)
            self.assertEqual(
                run.returncode,
                0,
                f"MADT trim regression test failed:\n{run.stdout}\n{run.stderr}",
            )


if __name__ == "__main__":
    unittest.main()
