/*
 * Host-side, hardware-free regression test for the MADT trimming in
 * Silicon/Apple/AppleSiliconPkg/Include/Drivers/NtasiMadtTrim.h.
 *
 * This file #includes that header directly -- the same text compiled into
 * AcpiPlatform.c under the EDK2/Clang toolchain -- and builds standalone with a
 * plain host C compiler. Run it with:
 *
 *   cc -std=c99 -Wall -Wextra -o /tmp/test_madt_adt_trim \
 *      Tests/test_madt_adt_trim.c && /tmp/test_madt_adt_trim
 *
 * or via Tests/test_madt_adt_trim.py, which does exactly that.
 *
 * WHAT IT PINS
 *
 * The SoC family packages generated by Tools/add-soc.py size their MADT to the
 * die, because that is what Asahi's device tree describes. Apple bins these
 * parts, so a machine can have fewer cores than the die. Publishing a GICC for
 * a core that is not there makes Windows issue PSCI CPU_ON for it and answer
 * the failure with SYSTEM_RESET, so the trim is what makes a die-sized table
 * safe.
 *
 * The case that matters is the sparse one. A 10-core M2 Pro is not the first
 * ten of the die's twelve: T6020J414sTopology.h records that "CPU slots 7 and
 * 11 are absent in the ADT". Dropping by count instead of by identity would
 * keep exactly the wrong two.
 *
 * Copyright (c) 2026 Aurora Silicon
 * SPDX-License-Identifier: MIT
 */

#include <stdio.h>
#include <string.h>

#include "../Silicon/Apple/AppleSiliconPkg/Include/Drivers/NtasiMadtTrim.h"

static int failures;

#define CHECK(cond, ...)                                   \
  do {                                                     \
    if (!(cond)) {                                         \
      printf("FAIL %s:%d: ", __FILE__, __LINE__);          \
      printf(__VA_ARGS__);                                 \
      printf("\n");                                        \
      failures++;                                          \
    }                                                      \
  } while (0)

/* A GICC is 80 bytes in ACPI 6.3; a GICR is 16. */
#define GICC_LEN  80u
#define GICR_LEN  16u

/*
 * Build a MADT with the given MPIDRs, followed by one GICR. Mirrors the shape
 * every generated MADT_Static.aslc emits.
 */
static NTASI_MADT_U64
build_madt (NTASI_MADT_U8 *buf, const NTASI_MADT_U64 *mpidrs, unsigned count)
{
  NTASI_MADT_U64  off = NTASI_MADT_HEADER_SIZE;
  unsigned        i, b;

  memset (buf, 0, 4096);
  memcpy (buf, "APIC", 4);

  for (i = 0; i < count; i++) {
    buf[off]      = NTASI_MADT_TYPE_GICC;
    buf[off + 1]  = GICC_LEN;
    /* AcpiProcessorUid, so a dropped entry is identifiable in the output. */
    buf[off + NTASI_MADT_GICC_UID_OFFSET] = (NTASI_MADT_U8)i;
    for (b = 0; b < 8; b++) {
      buf[off + NTASI_MADT_GICC_MPIDR_OFFSET + b] =
        (NTASI_MADT_U8)((mpidrs[i] >> (8 * b)) & 0xFFu);
    }
    off += GICC_LEN;
  }

  buf[off]     = NTASI_MADT_TYPE_GICR;
  buf[off + 1] = GICR_LEN;
  off += GICR_LEN;

  for (b = 0; b < 4; b++) {
    buf[NTASI_MADT_LENGTH_OFFSET + b] = (NTASI_MADT_U8)((off >> (8 * b)) & 0xFFu);
  }

  return off;
}

static NTASI_MADT_U32
gicr_range (const NTASI_MADT_U8 *buf, NTASI_MADT_U64 size)
{
  NTASI_MADT_U64  off = NTASI_MADT_HEADER_SIZE;

  while (off + 2 <= size) {
    if (buf[off] == NTASI_MADT_TYPE_GICR) {
      NTASI_MADT_U32  v = 0;
      unsigned        b;
      for (b = 0; b < 4; b++) {
        v |= ((NTASI_MADT_U32)buf[off + NTASI_MADT_GICR_RANGE_OFFSET + b]) << (8 * b);
      }
      return v;
    }
    off += buf[off + 1];
  }
  return 0;
}

/* Collects the UIDs still present, in order. */
static unsigned
surviving_uids (const NTASI_MADT_U8 *buf, NTASI_MADT_U64 size, NTASI_MADT_U8 *out)
{
  NTASI_MADT_U64  off = NTASI_MADT_HEADER_SIZE;
  unsigned        n   = 0;

  while (off + 2 <= size) {
    if (buf[off] == NTASI_MADT_TYPE_GICC) {
      out[n++] = buf[off + NTASI_MADT_GICC_UID_OFFSET];
    }
    off += buf[off + 1];
  }
  return n;
}

/* Predicate context: the ADT's /cpus/cpuN reg values. */
struct adt {
  const NTASI_MADT_U32  *regs;
  unsigned              count;
};

static NTASI_MADT_BOOL
adt_has (NTASI_MADT_CPU_ID id, void *ctx)
{
  const struct adt  *a = (const struct adt *)ctx;
  unsigned          i;

  for (i = 0; i < a->count; i++) {
    if (NtasiMadtCpuIdEquals (NtasiMadtCpuIdFromAdtReg (a->regs[i]), id)) {
      return NTASI_MADT_TRUE;
    }
  }
  return NTASI_MADT_FALSE;
}

static void
test_identity_mapping (void)
{
  /*
   * The two spellings have to agree. T6020 P-cluster 1 core 0 is MPIDR
   * 0x10100 in Asahi's tree and (die 0, cluster 1, core 0) in the ADT.
   */
  NTASI_MADT_CPU_ID  m = NtasiMadtCpuIdFromMpidr (0x10100ull);
  NTASI_MADT_CPU_ID  a = NtasiMadtCpuIdFromAdtReg (0x100u);

  CHECK (NtasiMadtCpuIdEquals (m, a), "0x10100 should equal ADT reg 0x100");
  CHECK (m.Die == 0 && m.Cluster == 1 && m.Core == 0,
         "0x10100 decoded as die %u cluster %u core %u", m.Die, m.Cluster, m.Core);

  /*
   * Aff2 separates P cores from E cores and must not participate: E core 0 of
   * cluster 0 and P core 0 of cluster 0 would be the same core, which is why
   * Apple never numbers a P cluster 0 on a part that has E cores.
   */
  CHECK (NtasiMadtCpuIdEquals (NtasiMadtCpuIdFromMpidr (0x10203ull),
                               NtasiMadtCpuIdFromAdtReg (0x203u)),
         "0x10203 should equal ADT reg 0x203");

  /*
   * The Ultra parts continue die 1 at cluster 8, so Aff1 carries die * 8 +
   * cluster. ADT reg spells the die separately at bits 14:11.
   */
  {
    NTASI_MADT_CPU_ID  d1 = NtasiMadtCpuIdFromMpidr (0x10900ull);   /* Aff1 = 9 */
    CHECK (d1.Die == 1 && d1.Cluster == 1 && d1.Core == 0,
           "Aff1=9 decoded as die %u cluster %u", d1.Die, d1.Cluster);
    CHECK (NtasiMadtCpuIdEquals (d1, NtasiMadtCpuIdFromAdtReg ((1u << 11) | (1u << 8))),
           "die 1 cluster 1 core 0 should agree across spellings");
  }
}

static void
test_sparse_bin (void)
{
  /*
   * The J414s case. The T6020 die is 4 E cores plus two 4-core P clusters; a
   * 10-core M2 Pro drops one core from each P cluster, and the ones it drops
   * are slots 7 and 11 -- the last of each cluster, not the last two overall.
   */
  static const NTASI_MADT_U64  die[12] = {
    0x00000, 0x00001, 0x00002, 0x00003,
    0x10100, 0x10101, 0x10102, 0x10103,
    0x10200, 0x10201, 0x10202, 0x10203,
  };
  static const NTASI_MADT_U32  adt[10] = {
    0x000, 0x001, 0x002, 0x003,
    0x100, 0x101, 0x102,
    0x200, 0x201, 0x202,
  };
  struct adt              ctx = { adt, 10 };
  NTASI_MADT_U8           buf[4096];
  NTASI_MADT_U8           uids[16];
  NTASI_MADT_U64          size = build_madt (buf, die, 12);
  NTASI_MADT_U64          before = size;
  NTASI_MADT_TRIM_RESULT  r;
  unsigned                n, i;
  static const NTASI_MADT_U8  want[10] = { 0, 1, 2, 3, 4, 5, 6, 8, 9, 10 };

  r = NtasiMadtTrim (buf, &size, adt_has, &ctx);

  CHECK (r.Rewritten, "a 12-core table against a 10-core ADT should be rewritten");
  CHECK (r.Kept == 10, "kept %u, want 10", r.Kept);
  CHECK (r.Dropped == 2, "dropped %u, want 2", r.Dropped);
  CHECK (size == before - 2 * GICC_LEN, "size %llu, want %llu",
         (unsigned long long)size, (unsigned long long)(before - 2 * GICC_LEN));

  n = surviving_uids (buf, size, uids);
  CHECK (n == 10, "%u GICCs survived, want 10", n);
  for (i = 0; i < n && i < 10; i++) {
    CHECK (uids[i] == want[i], "survivor %u is uid %u, want %u", i, uids[i], want[i]);
  }

  /* The redistributor must describe frames for the cores that remain. */
  CHECK (gicr_range (buf, size) == NTASI_MADT_GICR_FRAME_SIZE * 10,
         "GICR range 0x%x, want 0x%x", gicr_range (buf, size),
         NTASI_MADT_GICR_FRAME_SIZE * 10);

  /* And the table's own length has to move with it. */
  {
    NTASI_MADT_U32  len = 0;
    unsigned        b;
    for (b = 0; b < 4; b++) {
      len |= ((NTASI_MADT_U32)buf[NTASI_MADT_LENGTH_OFFSET + b]) << (8 * b);
    }
    CHECK (len == size, "header length %u, want %llu", len, (unsigned long long)size);
  }
}

static void
test_full_bin_is_untouched (void)
{
  static const NTASI_MADT_U64  die[8] = {
    0x00000, 0x00001, 0x00002, 0x00003,
    0x10100, 0x10101, 0x10102, 0x10103,
  };
  static const NTASI_MADT_U32  adt[8] = {
    0x000, 0x001, 0x002, 0x003, 0x100, 0x101, 0x102, 0x103,
  };
  struct adt              ctx = { adt, 8 };
  NTASI_MADT_U8           buf[4096], copy[4096];
  NTASI_MADT_U64          size = build_madt (buf, die, 8);
  NTASI_MADT_U64          before = size;
  NTASI_MADT_TRIM_RESULT  r;

  memcpy (copy, buf, sizeof (copy));
  r = NtasiMadtTrim (buf, &size, adt_has, &ctx);

  CHECK (!r.Rewritten, "a table matching the ADT should not be rewritten");
  CHECK (r.Kept == 8 && r.Dropped == 0, "kept %u dropped %u, want 8 and 0",
         r.Kept, r.Dropped);
  CHECK (size == before, "size changed on a full bin");
  CHECK (memcmp (buf, copy, (size_t)before) == 0, "table bytes changed on a full bin");
}

static NTASI_MADT_BOOL
never (NTASI_MADT_CPU_ID id, void *ctx)
{
  (void)id;
  (void)ctx;
  return NTASI_MADT_FALSE;
}

static void
test_nothing_matched_is_refused (void)
{
  /*
   * If the ADT encoding assumption were ever wrong, every GICC would look
   * absent. An MADT with no processors is unbootable, so the original has to
   * survive -- a table sized to the die is a better failure than an empty one.
   */
  static const NTASI_MADT_U64  die[4] = { 0x0, 0x1, 0x2, 0x3 };
  NTASI_MADT_U8           buf[4096], copy[4096];
  NTASI_MADT_U64          size = build_madt (buf, die, 4);
  NTASI_MADT_U64          before = size;
  NTASI_MADT_TRIM_RESULT  r;

  memcpy (copy, buf, sizeof (copy));
  r = NtasiMadtTrim (buf, &size, never, NULL);

  CHECK (!r.Rewritten, "an all-absent verdict must not be applied");
  CHECK (r.Kept == 0 && r.Dropped == 4, "kept %u dropped %u", r.Kept, r.Dropped);
  CHECK (size == before, "size changed when nothing matched");
  CHECK (memcmp (buf, copy, (size_t)before) == 0, "table changed when nothing matched");
}

static void
test_malformed_length_is_refused (void)
{
  /* A zero-length sub-structure would loop forever if it were trusted. */
  static const NTASI_MADT_U64  die[2] = { 0x0, 0x1 };
  static const NTASI_MADT_U32  adt[1] = { 0x000 };
  struct adt              ctx = { adt, 1 };
  NTASI_MADT_U8           buf[4096];
  NTASI_MADT_U64          size = build_madt (buf, die, 2);
  NTASI_MADT_U64          before = size;
  NTASI_MADT_TRIM_RESULT  r;

  buf[NTASI_MADT_HEADER_SIZE + 1] = 0;

  r = NtasiMadtTrim (buf, &size, adt_has, &ctx);
  CHECK (!r.Rewritten, "a malformed table must not be rewritten");
  CHECK (size == before, "size changed on a malformed table");
}

int
main (void)
{
  test_identity_mapping ();
  test_sparse_bin ();
  test_full_bin_is_untouched ();
  test_nothing_matched_is_refused ();
  test_malformed_length_is_refused ();

  if (failures != 0) {
    printf ("%d check(s) failed\n", failures);
    return 1;
  }
  printf ("all MADT trim checks passed\n");
  return 0;
}
