# Generated by Tools/add-machine.py from Asahi's t8112-j413.dts.
# Apple MacBook Air (13-inch, M2, 2022)
#
# UNVERIFIED ON HARDWARE. This compiles against a proven SoC family
# package with this machine's own identity; nothing here has been
# booted. Its ANS, display and input paths are inherited from the
# template (j813) and have not been checked on this machine.
#
# @file
# stuart settings for the MacBookAir13M2 platform.
#
# Everything except the platform name lives in Platform/PlatformBuildCommon.py.
# When this machine gains a feature set, add it to Platform/Features.py and
# set DEVICE here.
#
# Copyright (c) Microsoft Corporation.
# Copyright (c) 2026 Aurora Silicon
# SPDX-License-Identifier: BSD-2-Clause-Patent
##
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from PlatformBuildCommon import ApplePlatformBuilder, ApplePlatformSettings, stuart_main

from edk2toolext.environment.uefi_build import UefiBuilder
from edk2toolext.invocables.edk2_platform_build import BuildSettingsManager
from edk2toolext.invocables.edk2_pr_eval import PrEvalSettingsManager
from edk2toolext.invocables.edk2_setup import SetupSettingsManager
from edk2toolext.invocables.edk2_update import UpdateSettingsManager

PLATFORM = "MacBookAir13M2"
DEVICE = "j413"


class SettingsManager(ApplePlatformSettings, UpdateSettingsManager, SetupSettingsManager,
                      PrEvalSettingsManager):
    PLATFORM = PLATFORM


class PlatformBuilder(ApplePlatformBuilder, UefiBuilder, BuildSettingsManager):
    PLATFORM = PLATFORM
    DEVICE = DEVICE

    def __init__(self):
        UefiBuilder.__init__(self)


if __name__ == "__main__":
    stuart_main(__file__)
