/** @file
  Processor containers for the Apple T8122 family.

  Generated by Tools/add-soc.py from the device tree for
  Apple MacBook Air (13-inch, M3, 2024).

  Covers: t8122

  UNVERIFIED. Every address, core count and window below is what the device
  tree states; none of it has been read off this silicon by us, and no machine
  in this family has been booted. Treat a successful build as evidence that the
  package is self-consistent and nothing more.

  A separate SSDT rather than part of a board DSDT, because the CPU tree is a
  property of the die and the DSDT is a property of the board. Keeping it here
  is what lets one board package -- J414sBoardPkg, GenericBoardPkg -- serve
  machines built on different silicon.

  8 core(s) in 2 cluster(s) across 1 die(s).

  Scope (\_SB) is opened by the DSDT; this only adds to it.

  SPDX-License-Identifier: BSD-2-Clause-Patent OR MIT
**/

DefinitionBlock ("Cpus.aml", "SSDT", 0x02, "Apple", "T8122CPU", 0x8122) {
    Scope (\_SB) {
    Device (DIE0) {
        Name (_HID, "ACPI0010")
        Name (_UID, 0)

        // 4 efficiency core(s), device-tree cluster 0.
        Device (CL00) {
            Name (_HID, "ACPI0010")
            Name (_UID, 1)

            Device (C000) {
                Name (_HID, "ACPI0007")
                Name (_UID, 0)
                Name (_STR, Unicode ("Apple M3 Efficiency Core 0"))
                Name (_DDN, "Apple M3 Efficiency Core 0")
                Method (_STA) { Return (0xF) }
            }

            Device (C001) {
                Name (_HID, "ACPI0007")
                Name (_UID, 1)
                Name (_STR, Unicode ("Apple M3 Efficiency Core 1"))
                Name (_DDN, "Apple M3 Efficiency Core 1")
                Method (_STA) { Return (0xF) }
            }

            Device (C002) {
                Name (_HID, "ACPI0007")
                Name (_UID, 2)
                Name (_STR, Unicode ("Apple M3 Efficiency Core 2"))
                Name (_DDN, "Apple M3 Efficiency Core 2")
                Method (_STA) { Return (0xF) }
            }

            Device (C003) {
                Name (_HID, "ACPI0007")
                Name (_UID, 3)
                Name (_STR, Unicode ("Apple M3 Efficiency Core 3"))
                Name (_DDN, "Apple M3 Efficiency Core 3")
                Method (_STA) { Return (0xF) }
            }
        }

        // 4 performance core(s), device-tree cluster 1.
        Device (CL01) {
            Name (_HID, "ACPI0010")
            Name (_UID, 2)

            Device (C004) {
                Name (_HID, "ACPI0007")
                Name (_UID, 4)
                Name (_STR, Unicode ("Apple M3 Performance Core 0"))
                Name (_DDN, "Apple M3 Performance Core 0")
                Method (_STA) { Return (0xF) }
            }

            Device (C005) {
                Name (_HID, "ACPI0007")
                Name (_UID, 5)
                Name (_STR, Unicode ("Apple M3 Performance Core 1"))
                Name (_DDN, "Apple M3 Performance Core 1")
                Method (_STA) { Return (0xF) }
            }

            Device (C006) {
                Name (_HID, "ACPI0007")
                Name (_UID, 6)
                Name (_STR, Unicode ("Apple M3 Performance Core 2"))
                Name (_DDN, "Apple M3 Performance Core 2")
                Method (_STA) { Return (0xF) }
            }

            Device (C007) {
                Name (_HID, "ACPI0007")
                Name (_UID, 7)
                Name (_STR, Unicode ("Apple M3 Performance Core 3"))
                Name (_DDN, "Apple M3 Performance Core 3")
                Method (_STA) { Return (0xF) }
            }
        }
    }
    }
}
