#!/usr/bin/env python3
"""Create a Mu SoC family package from an Asahi device tree.

WHY THIS EXISTS, AND WHAT IT DELIBERATELY DOES NOT DO
-----------------------------------------------------
A family package is the part of the firmware that describes silicon rather than
a machine: where DRAM starts, where the MMIO windows are, how many cores there
are and how they cluster, where UART0 and the PCIe root complex live. Every one
of those is a fact Asahi's device tree already states, per SoC, maintained by
people who boot Linux on the hardware.

Hand-transcribing them does not go well. T602X's hand-written memory map left a
3GB hole containing ANS; it survived review and was only found when ANS was
enabled for the first time and the first SART register read took a translation
fault on real hardware. It still has a second hole over dcpext that nothing has
touched yet. Both are covered automatically by windows derived from the tree
that declares those nodes.

So this generates. What it generates is then *committed as static source and
owned by hand*, exactly like the platform packages Tools/add-machine.py makes:
the ACPI tables have to map hardware onto the device nodes Windows drivers bind
to, and that mapping -- _HID strings, _DSD names, GSIV renumbering, AML -- is
the work and exists in no device tree. This gets a family to the point where
that work can begin, and no further.

WHAT IT CANNOT KNOW
-------------------
Three things are not in any device tree and are emitted as explicit unknowns
rather than guesses:

  * AIC geometry -- IRQ counts, register strides, capability offsets. Linux and
    m1n1 both read these off the controller at runtime. CSRT.aslc is therefore
    generated as the same documented stub T810XFamilyPkg has shipped since the
    beginning, and the machine boots without it; it is Windows' HAL extension
    that needs it filled in.
  * Which core firmware boots on. Assumed to be UID 0, which is right for every
    SoC we have measured except T8142.
  * The bin. Apple ships several core counts per die and the tree describes the
    die. See the CPU-count note in the generated Readme.

    Tools/add-soc.py --list
    Tools/add-soc.py T811X --dtb Build/DeviceTree/t8112-j413.dtb --socs t8112
"""

from __future__ import annotations

import argparse
import shutil
import sys
import uuid
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(Path(__file__).resolve().parent))

import socfacts  # noqa: E402

SILICON = REPO / "Silicon/Apple"

# Deterministic GUIDs. A family package needs a package GUID, a token-space
# GUID and one FILE_GUID per module; generating them from the package name
# means re-running this tool is idempotent and two people generating the same
# package get the same file rather than a spurious diff.
GUID_NS = uuid.UUID("6f1c4f6a-6b0e-5a2e-9a37-2f4d9a2a1c00")


def guid(*parts: str) -> str:
    return str(uuid.uuid5(GUID_NS, "/".join(parts))).lower()


def guid_braced(*parts: str) -> str:
    u = uuid.uuid5(GUID_NS, "/".join(parts))
    b = u.bytes_le
    return ("{ 0x%08x, 0x%04x, 0x%04x, { %s } }"
            % (int.from_bytes(b[0:4], "little"),
               int.from_bytes(b[4:6], "little"),
               int.from_bytes(b[6:8], "little"),
               ", ".join("0x%02x" % x for x in b[8:16])))


def size_macro(n: int) -> str:
    """EDK2 spells sizes as SIZE_nGB / SIZE_nMB; fall back to hex."""
    for unit, div in (("GB", 1 << 30), ("MB", 1 << 20), ("KB", 1 << 10)):
        if n >= div and n % div == 0:
            v = n // div
            if v & (v - 1) == 0:
                return f"SIZE_{v}{unit}"
    return f"0x{n:X}"


def banner(soc_list, model):
    return f"""  Generated by Tools/add-soc.py from the device tree for
  {model}.

  Covers: {', '.join(soc_list)}

  UNVERIFIED. Every address, core count and window below is what the device
  tree states; none of it has been read off this silicon by us, and no machine
  in this family has been booted. Treat a successful build as evidence that the
  package is self-consistent and nothing more."""


# --------------------------------------------------------------------------
# Generators
# --------------------------------------------------------------------------

def gen_dec(name, facts, socs):
    pkg = f"{name}FamilyPkg"
    c = facts["cpu"]
    return f"""## @file
#  {pkg} -- Apple {', '.join(s.upper() for s in socs)} SoC family package description.
#
{chr(10).join('#' + l for l in banner(socs, facts['model']).splitlines())}
#
#  SPDX-License-Identifier: BSD-2-Clause-Patent
##

[Defines]
  DEC_SPECIFICATION              = 0x00010005
  PACKAGE_NAME                   = {pkg}
  PACKAGE_GUID                   = {guid(pkg, 'package')}
  PACKAGE_VERSION                = 1.0

[Includes.common]
  Include

[Guids.common]
  g{pkg}TokenSpaceGuid = {guid_braced(pkg, 'tokenspace')}

[PcdsPatchableInModule.common]
  #
  # {len(c['clusters'])} cluster(s), {c['cpu_count']} cores as the die is built:
{chr(10).join('  #   cluster %d: %d x %s-core' % (cl['id'], cl['count'], cl['kind']) for cl in c['clusters'])}
  #
  g{pkg}TokenSpaceGuid.PcdCoreCount|{c['cpu_count']}|UINT32|0x00004406
  g{pkg}TokenSpaceGuid.PcdClusterCount|{len(c['clusters'])}|UINT32|0x00004407
"""


def gen_dsc_inc(name, facts, socs):
    pkg = f"{name}FamilyPkg"
    c = facts["cpu"]
    dram = facts["memory_base"]
    # Both proven families put the SEC stack 12GB into DRAM and the boot-args /
    # ADT pointers 8.5GB in. Those offsets are m1n1's contract, not the SoC's,
    # so they carry across unchanged.
    sec_stack = dram + 12 * (1 << 30)
    bootargs = dram + 0x220000000
    adt = bootargs + 0x4000

    pcie = facts["pcie"]
    internal = pcie[0] if pcie else None
    mmio32 = mmio64 = None
    if internal:
        for r in internal["ranges"]:
            if r["space"] == "mem32" and mmio32 is None:
                mmio32 = r
            elif r["space"] == "mem64" and mmio64 is None:
                mmio64 = r

    if internal is None:
        pcie_block = """  #
  # NO PCIe. Asahi's device tree for this SoC does not describe a root complex,
  # so there is nothing to derive and nothing has been invented. Without it
  # there is no NVMe, which means no internal boot device.
  #
  # The values needed are the apcie node's reg[0] (ECAM) and its `ranges`
  # (the 32-bit non-prefetchable and 64-bit prefetchable BAR windows). Both are
  # in the ADT of any live machine in this family; AppleSiliconPciPlatformDxe
  # reads the same node at runtime.
  #
  gArmTokenSpaceGuid.PcdPciBusMin|0x0
  gArmTokenSpaceGuid.PcdPciBusMax|0xFF
  gAppleSiliconPkgTokenSpaceGuid.PcdPciBusCount|0x100
  gArmTokenSpaceGuid.PcdPciIoBase|0x0
  gArmTokenSpaceGuid.PcdPciIoSize|0x00010000
  gEfiMdePkgTokenSpaceGuid.PcdPciIoTranslation|0x0
"""
    else:
        pcie_block = f"""  #
  # PCIe, decoded from {internal['name']} in the device tree.
  #
  # EDK2 convention: *Base is the bus/child address and *Translation is what
  # gets added to reach the CPU-physical address.
  #
  gArmTokenSpaceGuid.PcdPciBusMin|0x0
  gArmTokenSpaceGuid.PcdPciBusMax|0xFF
  gAppleSiliconPkgTokenSpaceGuid.PcdPciBusCount|0x100
  gArmTokenSpaceGuid.PcdPciIoBase|0x0
  gArmTokenSpaceGuid.PcdPciIoSize|0x00010000
  gEfiMdePkgTokenSpaceGuid.PcdPciIoTranslation|0x0

  # 32-bit window, not prefetchable: child 0x{mmio32['child']:X} -> cpu 0x{mmio32['parent']:X}
  gArmTokenSpaceGuid.PcdPciMmio32Base|0x{mmio32['child']:X}
  gArmTokenSpaceGuid.PcdPciMmio32Size|0x{mmio32['size']:X}
  gAppleSiliconPkgTokenSpaceGuid.PcdPciMmio32Limit|0x{mmio32['child'] + mmio32['size'] - 1:X}
  gEfiMdePkgTokenSpaceGuid.PcdPciMmio32Translation|0x{mmio32['parent'] - mmio32['child']:X}

  # 64-bit window, prefetchable: child 0x{mmio64['child']:X} -> cpu 0x{mmio64['parent']:X} (1:1)
  gArmTokenSpaceGuid.PcdPciMmio64Base|0x{mmio64['child']:X}
  gArmTokenSpaceGuid.PcdPciMmio64Size|0x{mmio64['size']:X}
  gAppleSiliconPkgTokenSpaceGuid.PcdPciMmio64Limit|0x{mmio64['child'] + mmio64['size'] - 1:X}
  gEfiMdePkgTokenSpaceGuid.PcdPciMmio64Translation|0x0

  # ECAM: {internal['name']} reg[0], 0x{internal['ecam_size']:X} of config space.
  gEfiMdePkgTokenSpaceGuid.PcdPciExpressBaseAddress|0x{internal['ecam_base']:X}
  gAppleSiliconPkgTokenSpaceGuid.PcdPciExpressBarSize|0x10000000
  gAppleSiliconPkgTokenSpaceGuid.PcdPciExpressBarLimit|0x{internal['ecam_base'] + 0x10000000 - 1:X}
""" if mmio32 and mmio64 else """  # PCIe root complex present but its `ranges` did not decode into the
  # expected 32-bit + 64-bit window pair. Fill these in by hand.
"""

    return f"""#
# Apple {', '.join(s.upper() for s in socs)} SoC configuration.
#
{chr(10).join('#' + (' ' + l if l else '') for l in banner(socs, facts['model']).splitlines())}
#
# SPDX-License-Identifier: BSD-2-Clause-Patent
#

[PcdsPatchableInModule.common]
  #
  # Patched from the FDT at runtime. DRAM base is 0x{dram:X} on this family --
  # taken from the device tree's memory node, not inherited from a sibling SoC,
  # because the base moved between generations and the two proven families
  # disagree. Each platform defines {name.upper()}_SYSTEM_MEMORY_SIZE for its own
  # configuration before including this file.
  #
  gArmTokenSpaceGuid.PcdSystemMemoryBase|0x{dram:X}
  gArmTokenSpaceGuid.PcdSystemMemorySize|$({name.upper()}_SYSTEM_MEMORY_SIZE)
  gArmTokenSpaceGuid.PcdFdBaseAddress|0x0
  gArmTokenSpaceGuid.PcdFvBaseAddress|0x0
  gAppleSiliconPkgTokenSpaceGuid.PcdFrameBufferAddress|0x0
  gAppleSiliconPkgTokenSpaceGuid.PcdFrameBufferSize|0x0

[PcdsFixedAtBuild.common]
  #
  # Timer GSIVs. Arbitrary: on Apple silicon the architected timers are per-CPU
  # FIQs rather than GIC PPIs, so these numbers only have to agree between the
  # GTDT and whatever presents the interrupt.
  #
  gArmTokenSpaceGuid.PcdArmArchTimerSecIntrNum|19
  gArmTokenSpaceGuid.PcdArmArchTimerIntrNum|17
  gArmTokenSpaceGuid.PcdArmArchTimerHypIntrNum|20
  gArmTokenSpaceGuid.PcdArmArchTimerVirtIntrNum|18
  gAppleSiliconPkgTokenSpaceGuid.PcdAppleSartVersion|2

  #
  # Boot args and ADT pointers. These are FixedAtBuild -- unlike the memory base
  # above they are not patched at runtime, so a value outside DRAM is fatal
  # rather than merely wrong. DRAM + 0x220000000, the offset both proven
  # families use.
  #
  # UNVERIFIED: these must match where m1n1 actually deposits the boot args and
  # the ADT on this family. Inside DRAM is necessary, not sufficient.
  #
  gAppleSiliconPkgTokenSpaceGuid.PcdBootArgsPointer|0x{bootargs:X}
  gAppleSiliconPkgTokenSpaceGuid.PcdAdtPointer|0x{adt:X}
  gAppleSiliconPkgTokenSpaceGuid.PcdSmbiosCpuIdentifier|"{socs[0].upper()}"
  gAppleSiliconPkgTokenSpaceGuid.PcdSmbiosCpuModel|"{marketing_name(socs[0])}"

  #
  # UART0, from the device tree's serial0 alias. Note this moves between
  # generations and even within one -- T6030 and T6031 are both M3-class and
  # put it 0x108000000 apart -- so it is never safe to inherit.
  #
  gAppleSiliconPkgTokenSpaceGuid.PcdAppleUartBase|0x{facts['uart_base']:X}

  gAppleSiliconPkgTokenSpaceGuid.PcdAppleSocIdentifier|0x{facts['soc_id']:04X}
  gAppleSiliconPkgTokenSpaceGuid.PcdInitializeRamdisk|TRUE

  #
  # SEC phase stack, DRAM + 12GB, matching both proven families.
  #
  gAppleSiliconPkgTokenSpaceGuid.PcdSecPhaseStackBase|0x{sec_stack:X}

  gAppleSiliconPkgTokenSpaceGuid.PcdCoreCount|{facts['cpu']['cpu_count']}|UINT32|0x00004406
  gAppleSiliconPkgTokenSpaceGuid.PcdClusterCount|{len(c['clusters'])}|UINT32|0x00004407

  #
  # Apple silicon has no GIC. m1n1's hv_vgicv3_init() installs distributor and
  # redistributor MMIO hooks at exactly these addresses on the native-AIC path,
  # so they describe what the guest is actually given. They are set for every
  # build, AIC included: the MADT describes a GICv3 unconditionally, and leaving
  # these at their UINT64 default of 0 does not omit the GIC, it publishes one
  # at physical address 0 -- which Windows believes, maps, and faults on.
  #
  gArmTokenSpaceGuid.PcdGicDistributorBase|0xf00000000
  gArmTokenSpaceGuid.PcdGicRedistributorsBase|0xf10000000
  gEfiMdeModulePkgTokenSpaceGuid.PcdAcpiDefaultOemRevision|0x0000{facts['soc_id']:04X}

!if $(SECURE_BOOT_ENABLE) == TRUE
  gEmbeddedTokenSpaceGuid.PcdMemoryTypeEfiRuntimeServicesData|600
  gEmbeddedTokenSpaceGuid.PcdMemoryTypeEfiRuntimeServicesCode|400
  gEmbeddedTokenSpaceGuid.PcdMemoryTypeEfiBootServicesCode|1500
!else
  gEmbeddedTokenSpaceGuid.PcdMemoryTypeEfiRuntimeServicesData|300
  gEmbeddedTokenSpaceGuid.PcdMemoryTypeEfiRuntimeServicesCode|150
  gEmbeddedTokenSpaceGuid.PcdMemoryTypeEfiBootServicesCode|1000
!endif
  gEmbeddedTokenSpaceGuid.PcdMemoryTypeEfiBootServicesData|800
  gEmbeddedTokenSpaceGuid.PcdMemoryTypeEfiLoaderCode|10
  gEmbeddedTokenSpaceGuid.PcdMemoryTypeEfiLoaderData|0
  gEmbeddedTokenSpaceGuid.PcdPrePiCpuIoSize|40

  gEfiMdeModulePkgTokenSpaceGuid.PcdSrIovSupport|FALSE
  gEfiMdeModulePkgTokenSpaceGuid.PcdAriSupport|FALSE
  gEfiMdeModulePkgTokenSpaceGuid.PcdMrIovSupport|FALSE

{pcie_block}
  gEmbeddedTokenSpaceGuid.PcdDmaDeviceOffset|0xFFFFFFFB00000000

[LibraryClasses.common]
  MemoryInitPeiLib|{pkg}/Library/MemoryInitPeiLib/MemoryInitPeiLib.inf
  MsPlatformDevicesLib  |{pkg}/Library/MsPlatformDevicesLib/MsPlatformDevicesLib.inf

[Components.common]

  {pkg}/AcpiTables/CPUAcpiTables.inf
"""


MARKETING = {
    "t8103": "Apple M1", "t8112": "Apple M2", "t8122": "Apple M3",
    "t8132": "Apple M4", "t8142": "Apple M5",
    "t6000": "Apple M1 Pro", "t6001": "Apple M1 Max", "t6002": "Apple M1 Ultra",
    "t6020": "Apple M2 Pro", "t6021": "Apple M2 Max", "t6022": "Apple M2 Ultra",
    "t6030": "Apple M3 Pro", "t6031": "Apple M3 Max", "t6032": "Apple M3 Ultra",
    "t6034": "Apple M3 Max",
    # Not an M-series part. The MacBook Neo uses the phone/tablet-class A18 Pro.
    "t8140": "Apple A18 Pro",
}


def marketing_name(soc: str) -> str:
    return MARKETING.get(soc, soc.upper())


def pcie_windows(facts):
    """PCIe config and BAR windows a core-system window does not already cover.

    The core windows are the 1GB blocks around everything /soc declares, and on
    some SoCs the root complex sits inside one of them. Emitting the window
    twice would spend two entries of a fixed-size descriptor table mapping the
    same pages with the same attributes.
    """
    core = [(w["base"], w["base"] + w["size"]) for w in facts["mmio"]]

    def covered(base, size):
        return any(lo <= base and base + size <= hi for lo, hi in core)

    out = []
    for p in facts["pcie"]:
        cands = [(p["ecam_base"], 0x10000000, f"{p['name']} ({p['die']}) config space")]
        for r in p["ranges"]:
            if r["space"] in ("mem32", "mem64"):
                cands.append((r["parent"], r["size"],
                              f"{p['name']} {r['space']} BAR window"))
        for base, size, what in cands:
            if base is None or covered(base, size):
                continue
            out.append({"base": base, "size": size, "what": what})
    return out


def gen_memmap_header(name, facts, socs):
    pkg = f"{name}FamilyPkg"
    lines = []
    for i, w in enumerate(facts["mmio"], 1):
        lines.append(f"#define APPLE_CORE_SYSTEM_MMIO_RANGE_{i}_BASE 0x{w['base']:X}")
        lines.append(f"#define APPLE_CORE_SYSTEM_MMIO_RANGE_{i}_SIZE {size_macro(w['size'])}")
        lines.append("")

    pcie_lines = []
    for i, w in enumerate(pcie_windows(facts), 1):
        pcie_lines.append(f"// {w['what']}")
        pcie_lines.append(f"#define APPLE_PCIE_MMIO_RANGE_{i}_BASE 0x{w['base']:X}")
        pcie_lines.append(f"#define APPLE_PCIE_MMIO_RANGE_{i}_SIZE {size_macro(w['size'])}")
        pcie_lines.append("")
    n = len(pcie_windows(facts))

    return f"""/** @file
  Virtual memory map for the Apple {', '.join(s.upper() for s in socs)} family.

{banner(socs, facts['model'])}

  HOW THESE WERE CHOSEN

  Each core-system window is the 1GB-aligned block containing a `reg` that some
  node under /soc declares, coalesced with its neighbours. That is deliberately
  generous: the map is installed before any driver runs and nothing dereferences
  a window, so spanning a hole is free, whereas a peripheral outside every
  window faults the first time it is touched. T602X's hand-written map left a
  3GB hole containing ANS and it took a translation fault on real hardware to
  find it.

  PCIe windows are the root complex's own reg[0] plus the BAR windows decoded
  from its `ranges`. Thunderbolt root complexes are not described by Asahi's
  tree and are therefore absent here; the internal complex carrying NVMe,
  Wi-Fi and the card reader is present.

  @copyright Copyright (c) 2026.

  SPDX-License-Identifier: BSD-2-Clause-Patent

**/

#ifndef {name.upper()}_FAMILY_VIRTUAL_MEMORY_MAP_DEFINES_H_
#define {name.upper()}_FAMILY_VIRTUAL_MEMORY_MAP_DEFINES_H_

//
// Core system MMIO: PMGR, AIC, watchdog, GPIO, UART, DARTs, and every other
// peripheral the device tree places. {len(facts['mmio'])} window(s).
//
#define APPLE_CORE_SYSTEM_MMIO_RANGE_COUNT {len(facts['mmio'])}

{chr(10).join(lines)}//
// PCIe. {n} window(s).
//
#define APPLE_PCIE_MMIO_RANGE_COUNT {n}

{chr(10).join(pcie_lines)}#endif /* {name.upper()}_FAMILY_VIRTUAL_MEMORY_MAP_DEFINES_H_ */
"""


def topology_prefix(name, socs):
    return f"{socs[0].upper()}"


def gen_topology_header(name, facts, socs, boot_uid=0):
    p = topology_prefix(name, socs)
    c = facts["cpu"]
    defs = [
        f"#define {p}_CPU_COUNT     {c['cpu_count']:>4}",
        f"#define {p}_CLUSTER_COUNT {len(c['clusters']):>4}",
        "",
    ]
    for i, cl in enumerate(c["clusters"]):
        defs.append(f"#define {p}_CLUSTER{i}_CORE_COUNT {cl['count']:>4}   // {cl['kind']}-cores")
        defs.append(f"#define {p}_CLUSTER{i}_UID_BASE   {cl['uid_base']:>4}")
        if cl["l2_size"]:
            defs.append(f"#define {p}_CLUSTER{i}_L2_SIZE    0x{cl['l2_size']:08X}")
        else:
            defs.append(f"// {p}_CLUSTER{i}_L2_SIZE is not defined: the device tree "
                        "states no cache-size for this cluster.")

        defs.append(f"#define {p}_CLUSTER{i}_EFFICIENCY {0 if cl['kind'] == 'E' else 1:>4}")
        defs.append("")

    return f"""/** @file
  CPU topology for the Apple {', '.join(s.upper() for s in socs)} family.

{banner(socs, facts['model'])}

  THE CORE COUNT IS THE DIE, NOT THE MACHINE

  Apple bins these parts. The device tree describes the die as fabricated, and a
  given machine may have fewer cores fused on -- an M2 Pro die carries 12 and
  ships as 10 or 12, an M4 die carries 10 and ships as 8 or 10. Publishing a
  GICC for a core that is not there is not harmless: Windows issues PSCI CPU_ON
  for every enabled entry, and a truthful failure is answered with SYSTEM_RESET.

  AcpiPlatformDxe trims the MADT to the CPUs the live ADT reports before
  installing it, which is what makes a die-sized table safe here. The counts
  below are the ceiling that sizes the table.

  EFFICIENCY CLASS

  ACPI 6.3 defines a LOWER Processor Power Efficiency Class as MORE efficient,
  so E-cores are 0 and P-cores 1. That is what T6020J414sTopology.h does and
  what is emitted here. T8142J813Topology.h emits the opposite and documents
  why; do not copy it.

  SPDX-License-Identifier: BSD-2-Clause-Patent OR MIT
**/

#ifndef {p}_TOPOLOGY_H_
#define {p}_TOPOLOGY_H_

{chr(10).join(defs)}//
// The core the firmware boots on must be the MADT's first GICC entry
// (ACPI 6.3 section 5.2.12.14). UID 0 is correct for every SoC we have
// measured except T8142, where m1n1 comes up on a P-core. UNVERIFIED here.
//
#define {p}_BOOT_CPU_UID {boot_uid}

//
// Architected timer GSIVs, kept in step with {name}FamilyPkg.dsc.inc. Arbitrary:
// the timers are per-CPU FIQs on this silicon, not GIC PPIs.
//
#define {p}_GTDT_SECURE_EL1_GSIV    19
#define {p}_GTDT_NONSECURE_EL1_GSIV 17
#define {p}_GTDT_VIRTUAL_EL1_GSIV   18
#define {p}_GTDT_NONSECURE_EL2_GSIV 20

//
// Interrupt controller base, from the device tree. The geometry that goes with
// it -- IRQ counts, register strides, capability offsets -- is NOT in any
// device tree; Linux and m1n1 both read it off the controller at runtime. See
// CSRT.aslc.
//
#define {p}_AIC_BASE 0x{facts['aic']['base'] if facts['aic'] else 0:016X}ULL
#define {p}_AIC_SIZE 0x{facts['aic']['size'] if facts['aic'] else 0:016X}ULL

#endif /* {p}_TOPOLOGY_H_ */
"""


def body_lines(lines):
    return lines


def gen_cpus_asi(name, facts, socs):
    """The DSDT's processor container tree, as silicon-tier data.

    A DSDT is a board table, but its \\_SB CPU tree is not a property of the
    board -- it is the die's topology, spelled in AML. Keeping it inside each
    board's DSDT is what made every T602X machine carry J414s' ten-core tree
    regardless of its own silicon. Emitting it here lets a board DSDT say
    #include <Acpi/Cpus.asi> and get the topology of the SoC it was built for.

    ACPI0010 is the processor container HID and ACPI0007 the processor HID.

    THE BIN, AGAIN

    This is the die, so on a binned machine it names cores that are not fused
    on, and their _STA still answers 0xF. That is an overstatement but not the
    dangerous one: Windows enumerates processors from the MADT -- which
    AcpiPlatformDxe trims against the live ADT -- and correlates DSDT devices to
    it by _UID. A device with no MADT entry backs no processor and is not
    started. Making _STA answer honestly needs a value only the ADT knows, so it
    would have to be patched at install time the way the MADT is; worth doing,
    not needed for the boot to be correct.
    """
    c = facts["cpu"]
    marketing = marketing_name(socs[0])
    dies = {}
    for cl in c["clusters"]:
        dies.setdefault(0 if cl["id"] < 8 else 1, []).append(cl)

    #
    # An ACPI name segment is exactly four characters (ACPI 6.4, 20.2.2), so the
    # obvious CPU0..CPU31 and CLU0..CLU10 spellings break the moment a part has
    # more than ten of either -- and the Ultra parts number their second die's
    # clusters 8, 9 and 10. Zero-padded fixed-width names hold for every part
    # here: 32 cores on an M3 Ultra and six clusters per die.
    #
    def cpu_name(uid):
        return "C%03d" % uid

    def cluster_name(cid):
        return "CL%02d" % cid

    out = []
    for die, clusters in sorted(dies.items()):
        out.append(f"Device (DIE{die}) {{")
        out.append('    Name (_HID, "ACPI0010")')
        out.append(f"    Name (_UID, {die})")
        for idx, cl in enumerate(clusters):
            kind = "Efficiency" if cl["kind"] == "E" else "Performance"
            out.append("")
            out.append(f"    // {cl['count']} {kind.lower()} core(s), device-tree cluster {cl['id']}.")
            out.append(f"    Device ({cluster_name(cl['id'])}) {{")
            out.append('        Name (_HID, "ACPI0010")')
            out.append(f"        Name (_UID, {cl['id'] + 1})")
            for i in range(cl["count"]):
                uid = cl["uid_base"] + i
                label = f"{marketing} {kind} Core {i}"
                out.append("")
                out.append(f"        Device ({cpu_name(uid)}) {{")
                out.append('            Name (_HID, "ACPI0007")')
                out.append(f"            Name (_UID, {uid})")
                out.append(f'            Name (_STR, Unicode ("{label}"))')
                out.append(f'            Name (_DDN, "{label}")')
                out.append("            Method (_STA) { Return (0xF) }")
                out.append("        }")
            out.append("    }")
        out.append("}")

    body = "\n".join("    " + l if l else "" for l in body_lines(out))
    return f"""/** @file
  Processor containers for the Apple {', '.join(s.upper() for s in socs)} family.

{banner(socs, facts['model'])}

  A separate SSDT rather than part of a board DSDT, because the CPU tree is a
  property of the die and the DSDT is a property of the board. Keeping it here
  is what lets one board package -- J414sBoardPkg, GenericBoardPkg -- serve
  machines built on different silicon.

  {c['cpu_count']} core(s) in {len(c['clusters'])} cluster(s) across {len(dies)} die(s).

  Scope (\\_SB) is opened by the DSDT; this only adds to it.

  SPDX-License-Identifier: BSD-2-Clause-Patent OR MIT
**/

DefinitionBlock ("Cpus.aml", "SSDT", 0x02, "Apple", "{socs[0].upper()}CPU", 0x{facts['soc_id']:04X}) {{
    Scope (\\_SB) {{
{body}
    }}
}}
"""

def gen_madt(name, facts, socs, boot_uid=0):
    p = topology_prefix(name, socs)
    c = facts["cpu"]

    # ACPI 6.3 5.2.12.14: the bootstrap processor must be the first GICC.
    entries = []
    for cl in c["clusters"]:
        for i, mpidr in enumerate(cl["mpidrs"]):
            uid = cl["uid_base"] + i
            aff = (0, (mpidr >> 16) & 0xFF, (mpidr >> 8) & 0xFF, mpidr & 0xFF)
            entries.append({
                "uid": uid,
                "aff": aff,
                "eff": 0 if cl["kind"] == "E" else 1,
                "label": f"cluster {cl['id']} {cl['kind']}-core {i}",
            })
    #
    # ACPI 6.3 5.2.12.14 requires the bootstrap processor's GICC to be first.
    # That is not always UID 0: firmware comes up on a P-core on T8142 and on
    # T8140, where the ADT numbers it physical CPU 4. Listing an E-core first
    # there describes a processor the OS is not running on.
    #
    boot_index = next((i for i, e in enumerate(entries) if e["uid"] == boot_uid), 0)
    if boot_index != 0:
        entries.insert(0, entries.pop(boot_index))
    boot = entries[0]
    rest = entries[1:]

    def emit(e):
        return (f"    EFI_ACPI_6_3_GICC_STRUCTURE_INIT( // {e['label']}\n"
                f"        {e['uid']}, {e['uid']}, GET_MPIDR({e['aff'][0]}, {e['aff'][1]}, "
                f"{e['aff'][2]}, {e['aff'][3]}), EFI_ACPI_6_3_GIC_ENABLED,\n"
                f"        {p}_PMU_IRQ_UNKNOWN, 0, 0, 0, 25, 0 /* GicRBase */, {e['eff']}, 0),")

    return f"""/**
 * Multiple APIC Description Table for the Apple {', '.join(s.upper() for s in socs)} family.
 *
{chr(10).join(' * ' + l.strip() if l.strip() else ' *' for l in banner(socs, facts['model']).splitlines())}
 *
 * SPDX-License-Identifier: BSD-2-Clause-Patent OR MIT
 */

#include <Library/AcpiLib.h>
#include <Library/ArmLib.h>
#include <Library/PcdLib.h>
#include <IndustryStandard/Acpi63.h>
#include <Acpi/AcpiHeader.h>
#include "{p}Topology.h"

//
// PMU interrupt indices. Asahi's tree expresses these as AIC_CPU_PMU_E /
// AIC_CPU_PMU_P fiq-index affinities rather than plain GSIVs, so there is no
// number here to copy. 0 means "no PMU interrupt", which is the honest
// representation. Do not import the values from another SoC package.
//
#define {p}_PMU_IRQ_UNKNOWN 0

#define MADT_GICR_INIT()  {{                                                    \\
   EFI_ACPI_6_4_GICR,                        /* Type */                       \\
   sizeof (EFI_ACPI_6_4_GICR_STRUCTURE),     /* Length */                     \\
   EFI_ACPI_RESERVED_WORD,                   /* Reserved */                   \\
   FixedPcdGet32 (PcdGicRedistributorsBase), /* DiscoveryRangeBaseAddress */  \\
   0x20000 * FixedPcdGet32 (PcdCoreCount)    /* DiscoveryRangeLength */       \\
}}

#pragma pack (1)

typedef struct {{
  EFI_ACPI_6_3_MULTIPLE_APIC_DESCRIPTION_TABLE_HEADER  Header;
  EFI_ACPI_6_3_GIC_STRUCTURE                           GicInterfaces[{p}_CPU_COUNT];
  EFI_ACPI_6_0_GIC_DISTRIBUTOR_STRUCTURE               GicDistributor;
  EFI_ACPI_6_4_GICR_STRUCTURE                          GicRedistributor;
  //
  // No GIC ITS entry. The distributor and redistributor above are emulated by
  // m1n1's vGIC carrier; the ITS is not -- its MMIO hook is compiled out
  // whenever the native-AIC bridge is in use, which is every configuration this
  // platform ships. Advertising one is not a harmless overstatement: Windows
  // initialises every ITS the MADT lists and the first register read lands on
  // an address with no stage-2 mapping, which ends the boot.
  //
  // It is also the accurate description of the machine. Apple silicon has no
  // GIC, MSIs are translated nowhere, and every peripheral interrupt -- PCIe
  // included -- arrives through AIC and is bridged as a wired interrupt.
  //
}} MULTIPLE_APIC_DESCRIPTION_TABLE;

#pragma pack ()

MULTIPLE_APIC_DESCRIPTION_TABLE  Madt = {{
  {{
    __ACPI_HEADER (
      EFI_ACPI_6_3_MULTIPLE_APIC_DESCRIPTION_TABLE_SIGNATURE,
      MULTIPLE_APIC_DESCRIPTION_TABLE,
      EFI_ACPI_6_3_MULTIPLE_APIC_DESCRIPTION_TABLE_REVISION
    ),
    0, // LocalApicAddress
    0, // Flags
  }},
  {{
    //
    // EFI_ACPI_6_3_GICC_STRUCTURE_INIT(GicId, AcpiCpuUid, Mpidr, Flags, PmuIrq,
    //     GicBase, GicVBase, GicHBase, GsivId, GicRBase, Efficiency, SpeOvflIrq)
    //
    // The bootstrap processor's GICC must come first (ACPI 6.3 5.2.12.14).
    // UNVERIFIED which core that is on this family -- see {p}_BOOT_CPU_UID.
    //
    // The table is sized to the die. AcpiPlatformDxe removes entries for cores
    // the live ADT does not report before installing it, because leaving a
    // phantom core enabled makes Windows issue PSCI CPU_ON for it and answer
    // the failure with SYSTEM_RESET.
    //
{emit(boot)}

{chr(10).join(emit(e) for e in rest)}
  }},
  EFI_ACPI_6_0_GIC_DISTRIBUTOR_INIT (0, FixedPcdGet64 (PcdGicDistributorBase), 0, 3),
  MADT_GICR_INIT ()
}};

//
// Reference the table so the optimiser cannot drop it.
//
VOID *CONST  ReferenceAcpiTable = &Madt;
"""


def macro(lines, width=84):
    """Join lines into a C macro body, padding each to `width` before its \\.

    Generated macros span many lines and a single missing continuation turns the
    rest of the body into stray top-level tokens, so this is the only place that
    decides where a backslash goes.
    """
    out = []
    for i, line in enumerate(lines):
        if i == len(lines) - 1:
            out.append(line)
        else:
            out.append(line.ljust(width) + "\\")
    return "\n".join(out)


def gen_pptt(name, facts, socs):
    p = topology_prefix(name, socs)
    c = facts["cpu"]
    clusters = c["clusters"]

    # Ultra parts put die 1's clusters at Aff1 >= 8. Group by that so the PPTT
    # describes two dies rather than one die with six clusters.
    dies = {}
    for i, cl in enumerate(clusters):
        dies.setdefault(0 if cl["id"] < 8 else 1, []).append((i, cl))
    die_count = len(dies)
    per_die = dies[0]

    types = []
    for i, cl in per_die:
        types.append(f"""typedef struct {{
  EFI_ACPI_6_4_PPTT_STRUCTURE_PROCESSOR  Cluster;
  PPTT_CORE                              Cores[{cl['count']}];
}} PPTT_CLUSTER_{i};""")

    die_members = "\n".join(f"  PPTT_CLUSTER_{i}  Cluster{i};" for i, _ in per_die)

    cluster_macros = []
    for i, cl in per_die:
        body = [
            f"#define CLUSTER_{i}_INIT(DieId)",
            "{",
            "  EFI_ACPI_6_4_PPTT_STRUCTURE_PROCESSOR_INIT (",
            f"    OFFSET_OF (PPTT_CLUSTER_{i}, Cores),                    /* Length */",
            "    PPTT_PROCESSOR_CLUSTER_FLAGS,                          /* Flag */",
            "    OFFSET_OF (EFI_ACPI_6_4_PROCESSOR_PROPERTIES_TOPOLOGY_TABLE,",
            "      Dies[DieId].Die),                                    /* Parent */",
            f"    (((DieId) << 4) | {i}),                                  /* ACPI Id */",
            "    0                                                      /* Private resources */",
            "  ),",
            "  {",
        ]
        body += [f"    CORE_INIT (DieId, {i}, {j})," for j in range(cl["count"] - 1)]
        body += [f"    CORE_INIT (DieId, {i}, {cl['count'] - 1})"]
        body += ["  }", "}"]
        cluster_macros.append(macro(body))

    uid_expr = []
    for i, cl in per_die:
        uid_expr.append(f"#define CLUSTER_{i}_UID_BASE {cl['uid_base']}")

    core_init_macro = macro([
        "#define CORE_INIT(DieId, ClusterIdx, CpuId)",
        "{",
        "  EFI_ACPI_6_4_PPTT_STRUCTURE_PROCESSOR_INIT (",
        "    0x14,                                                  /* Length */",
        "    PPTT_PROCESSOR_CORE_FLAGS,                             /* Flag */",
        "    OFFSET_OF (EFI_ACPI_6_4_PROCESSOR_PROPERTIES_TOPOLOGY_TABLE,",
        "      Dies[DieId].Cluster ## ClusterIdx),                  /* Parent */",
        f"    (({p}_CPU_COUNT / DIE_COUNT) * (DieId)) +",
        "      CLUSTER_ ## ClusterIdx ## _UID_BASE + (CpuId),       /* ACPI Id */",
        "    0                                                      /* Private resources */",
        "  ),",
        "}",
    ])

    die_body = [
        "#define DIE_INIT(DieId)",
        "{",
        "  EFI_ACPI_6_4_PPTT_STRUCTURE_PROCESSOR_INIT (",
        "    OFFSET_OF (PPTT_DIE, Cluster0),                        /* Length */",
        "    PPTT_PROCESSOR_PACKAGE_FLAGS,                 /* Flag */",
        "    0,                                                     /* Parent */",
        "    (DieId),                                               /* ACPI Id */",
        "    0                                                      /* Private resources */",
        "  ),",
    ]
    die_body += [f"  CLUSTER_{i}_INIT (DieId)," for i, _ in per_die[:-1]]
    die_body += [f"  CLUSTER_{per_die[-1][0]}_INIT (DieId)", "}"]
    die_init_macro = macro(die_body)
    dies_init = ",\n".join(f"  DIE_INIT ({d})" for d in sorted(dies))

    return f"""/**
 * Processor Properties Topology Table for the Apple {', '.join(s.upper() for s in socs)} family.
 *
{chr(10).join(' * ' + l.strip() if l.strip() else ' *' for l in banner(socs, facts['model']).splitlines())}
 *
 * Describes {die_count} die(s), {len(per_die)} cluster(s) per die, {c['cpu_count'] // die_count} cores per die.
 *
 * SPDX-License-Identifier: BSD-2-Clause-Patent OR MIT
 */

#include <Library/AcpiLib.h>
#include <Library/ArmLib.h>
#include <Library/PcdLib.h>
#include <IndustryStandard/Acpi64.h>
#include <Acpi/AcpiHeader.h>
#include <Acpi/SgiAcpiHeader.h>
#include "{p}Topology.h"

#define DIE_COUNT  {die_count}

//
// UID bases per cluster, matching the MADT's GICC UIDs exactly. The DSDT's
// _UID values, the MADT and this table all have to agree or the OS cannot
// correlate a processor with its place in the topology.
//
{chr(10).join(uid_expr)}

#pragma pack(1)

typedef struct {{
  EFI_ACPI_6_4_PPTT_STRUCTURE_PROCESSOR  Core;
}} PPTT_CORE;

{chr(10).join(types)}

typedef struct {{
  EFI_ACPI_6_4_PPTT_STRUCTURE_PROCESSOR  Die;
{die_members}
}} PPTT_DIE;

typedef struct {{
  EFI_ACPI_DESCRIPTION_HEADER  Header;
  PPTT_DIE                     Dies[DIE_COUNT];
}} EFI_ACPI_6_4_PROCESSOR_PROPERTIES_TOPOLOGY_TABLE;

#pragma pack ()

{core_init_macro}

{(chr(10)+chr(10)).join(cluster_macros)}

{die_init_macro}

EFI_ACPI_6_4_PROCESSOR_PROPERTIES_TOPOLOGY_TABLE  Pptt = {{
  __ACPI_HEADER (
    EFI_ACPI_6_4_PROCESSOR_PROPERTIES_TOPOLOGY_TABLE_STRUCTURE_SIGNATURE,
    EFI_ACPI_6_4_PROCESSOR_PROPERTIES_TOPOLOGY_TABLE,
    EFI_ACPI_6_4_PROCESSOR_PROPERTIES_TOPOLOGY_TABLE_REVISION
  ),
  {{
{dies_init}
  }}
}};

VOID *CONST  ReferenceAcpiTable = &Pptt;
"""


def gen_csrt(name, facts, socs):
    p = topology_prefix(name, socs)
    aic = facts["aic"]
    aic_compat = aic["compatible"][0] if aic else "unknown"
    version = "3" if "aic3" in aic_compat else "2" if "aic2" in (aic["compatible"] if aic else []) else "1"
    return f"""/**
 * Core System Resource Table for the Apple {', '.join(s.upper() for s in socs)} family.
 *
 * WHY THIS IS EMPTY
 *
 * Apple platforms implement two core system resources that are not architected:
 * the interrupt controller and the IOMMU. The CSRT is how firmware tells
 * Windows they are there, and it is what Windows' AIC HAL extension binds to.
 *
 * It is empty because the AIC payload cannot be derived. The device tree gives
 * the controller's base address ({p}_AIC_BASE, 0x{aic['base'] if aic else 0:X}) and its
 * compatible string ("{aic_compat}", i.e. AICv{version}) and stops there. Everything
 * else the table has to carry -- the IRQ count, the maximum IRQ, the die count,
 * and the EXTINTRCFG / INTMASKSET / INTMASKCLEAR strides -- is read off the
 * controller's own CAP0 and MAXNUMIRQ registers and out of the live ADT. Linux
 * does this at runtime and so does m1n1, which prints the whole geometry in one
 * line during boot:
 *
 *   AIC3 with 1/2 dies, 2400/4096 IRQs, reg_size:40004, config:10000,
 *   extintrcfg_stride:04a00, intmaskset_stride:04a00, intmaskclear_stride:04a00
 *
 * Transcribing that line from a machine in this family, plus the GSIV alias
 * pairs, is what completes this table. T8142FamilyPkg/AcpiTables/CSRT.aslc is
 * the worked example and T8142J813Topology.h documents each field.
 *
 * The strides in particular must be copied, never recomputed: m1n1 derives a
 * fallback from the register layout and the ADT then overrides it, and the two
 * differ by 0x200 per die. That is harmless on a one-die part, which is exactly
 * what would let the mistake survive review and bite on a two-die one.
 *
 * WHAT WORKS WITHOUT IT
 *
 * Everything except Windows' interrupt handling. UEFI drives AIC through
 * AppleAicDxe, which reads the controller directly and already handles v1, v2
 * and v3 from one code path, so firmware boots and the machine is usable over
 * serial and framebuffer. T810XFamilyPkg has shipped this same stub since the
 * beginning.
 *
 * SPDX-License-Identifier: BSD-2-Clause-Patent OR MIT
 */
"""


def gen_cpu_acpi_inf(name, facts, socs, cpu_ssdt=True):
    pkg = f"{name}FamilyPkg"
    cpus_source = "  Cpus.asl\n" if cpu_ssdt else (
        "  #\n"
        "  # No Cpus.asl. A board this family serves declares its own processor\n"
        "  # devices in its DSDT, and two declarations of \\_SB.DIE0 collide in one\n"
        "  # namespace. The board keeps them; see the family Readme.\n"
        "  #\n")
    return f"""## @file
#  ACPI tables describing the Apple {', '.join(s.upper() for s in socs)} processor complex.
#
#  SPDX-License-Identifier: BSD-2-Clause-Patent
##

[Defines]
  INF_VERSION                    = 0x00010005
  BASE_NAME                      = CPUAcpiTables
  FILE_GUID                      = {guid(pkg, 'CPUAcpiTables')}
  MODULE_TYPE                    = USER_DEFINED
  VERSION_STRING                 = 1.0

[Sources]
  #
  # CSRT.aslc is NOT listed. It is a documented stub on this family -- the AIC
  # geometry it needs has not been read off the hardware -- and a comment-only
  # .aslc compiles to an object with no ReferenceAcpiTable, which fails the
  # link rather than producing an empty table. Add it here in the same commit
  # that fills it in, exactly as T810XFamilyPkg leaves it out today.
  #
{cpus_source}  GTDT.aslc
  MADT_Static.aslc
  PPTT.aslc

[Packages]
  MdePkg/MdePkg.dec
  MdeModulePkg/MdeModulePkg.dec
  EmbeddedPkg/EmbeddedPkg.dec
  ArmPkg/ArmPkg.dec
  ArmPlatformPkg/ArmPlatformPkg.dec
  AppleSiliconPkg/AppleSiliconPkg.dec
  {pkg}/{pkg}.dec

[FixedPcd]
  gArmTokenSpaceGuid.PcdArmArchTimerSecIntrNum
  gArmTokenSpaceGuid.PcdArmArchTimerIntrNum
  gArmTokenSpaceGuid.PcdArmArchTimerHypIntrNum
  gArmTokenSpaceGuid.PcdArmArchTimerVirtIntrNum
  gArmTokenSpaceGuid.PcdGicDistributorBase
  gArmTokenSpaceGuid.PcdGicRedistributorsBase
  gAppleSiliconPkgTokenSpaceGuid.PcdCoreCount
  gEfiMdeModulePkgTokenSpaceGuid.PcdAcpiDefaultOemId
  gEfiMdeModulePkgTokenSpaceGuid.PcdAcpiDefaultOemTableId
  gEfiMdeModulePkgTokenSpaceGuid.PcdAcpiDefaultOemRevision
  gEfiMdeModulePkgTokenSpaceGuid.PcdAcpiDefaultCreatorId
  gEfiMdeModulePkgTokenSpaceGuid.PcdAcpiDefaultCreatorRevision
"""


def gen_readme(name, facts, socs, machines, caveats=""):
    pkg = f"{name}FamilyPkg"
    c = facts["cpu"]
    rows = "\n".join(
        f"| cluster {cl['id']} | {cl['count']} | {cl['kind']} | "
        f"{cl['uid_base']}..{cl['uid_base'] + cl['count'] - 1} | 0x{cl['l2_size'] or 0:X} |"
        for cl in c["clusters"])
    return f"""# {pkg}

{', '.join(marketing_name(s) for s in socs)} ({', '.join(s.upper() for s in socs)}).

Generated by `Tools/add-soc.py` from the device tree for {facts['model']}
(`Silicon/Apple/AppleSiliconPkg/DeviceTree/`, provenance in `SOURCE.json`), then
owned by hand.

## Status

**UNVERIFIED.** No machine in this family has been booted. Everything below is
what the device tree states.

## What the tree gave us

| | |
|---|---|
| DRAM base | `0x{facts['memory_base']:X}` |
| UART0 | `0x{facts['uart_base']:X}` |
| Interrupt controller | `0x{facts['aic']['base'] if facts['aic'] else 0:X}` ({facts['aic']['compatible'][0] if facts['aic'] else 'n/a'}) |
| MMIO windows | {len(facts['mmio'])} |
| PCIe root complexes | {len(facts['pcie'])} |

| cluster | cores | type | UIDs | L2 |
|---|---|---|---|---|
{rows}

## What still needs hardware

1. **CSRT / AIC geometry.** IRQ counts and register strides are read off the
   controller at runtime, not declared anywhere. See `AcpiTables/CSRT.aslc`.
   Windows' AIC HAL extension needs it; UEFI does not.
2. **Which core boots.** Assumed UID 0.
3. **Boot-args and ADT pointers.** Placed at the offset both proven families
   use; must be confirmed against m1n1 on this silicon.
4. **The bin.** The core count above is the die. `AcpiPlatformDxe` trims the
   MADT to what the live ADT reports, so a smaller machine is handled, but the
   PPTT is not trimmed.

## What needs nothing

NVMe and the interrupt controller are already generation-agnostic.
`AppleNANDStorageDxe` takes every address from the live ADT (`/arm-io/ans`,
`/arm-io/sart-ans`) and has only two register-map variants, selected from the
ADT. `AppleAicDxe` drives v1, v2 and v3 from one path with the layout read off
the controller.

## Machines

{chr(10).join('- ' + m for m in machines) if machines else '- none registered yet'}
{caveats}"""


# --------------------------------------------------------------------------
# Files copied from a proven family, with the family's identity substituted
# --------------------------------------------------------------------------

def copy_from_template(name, template, facts, socs):
    """MemoryInitPeiLib, MsPlatformDevicesLib and GTDT.

    These carry no SoC-specific data of their own -- the memory-init library
    reads its window list from the generated header, the device library only
    describes the console, and the GTDT is entirely PCD-driven. Copying keeps
    one implementation rather than a generated near-duplicate per family.
    """
    src = SILICON / f"{template}FamilyPkg"
    dst = SILICON / f"{name}FamilyPkg"
    pkg = f"{name}FamilyPkg"
    tpkg = f"{template}FamilyPkg"

    for rel in ("Library/MemoryInitPeiLib", "Library/MsPlatformDevicesLib"):
        shutil.copytree(src / rel, dst / rel)

    shutil.copy(src / "AcpiTables/GTDT.aslc", dst / "AcpiTables/GTDT.aslc")

    for path in list(dst.rglob("*.c")) + list(dst.rglob("*.inf")) + list(dst.rglob("*.aslc")):
        text = path.read_text(encoding="utf-8")
        text = (text.replace(tpkg, pkg)
                    .replace(f"{template}Family", f"{name}Family")
                    .replace(template, name.upper() if template.isupper() else name))
        if path.suffix == ".inf":
            # FILE_GUID must be unique per module or the build silently keeps
            # only one of the two.
            import re
            text = re.sub(r"(FILE_GUID\s*=\s*)[0-9a-fA-F-]{36}",
                          lambda m: m.group(1) + guid(pkg, path.parent.name),
                          text)
        path.write_text(text, encoding="utf-8")

    # The window list is the one part of the memory-init library that is data.
    mem = dst / "Library/MemoryInitPeiLib/MemoryInitPeiLib.c"
    text = mem.read_text(encoding="utf-8")
    core = "\n".join(
        f"  MAP_DEVICE_RANGE (APPLE_CORE_SYSTEM_MMIO_RANGE_{i}_BASE,  "
        f"APPLE_CORE_SYSTEM_MMIO_RANGE_{i}_SIZE);"
        for i in range(1, len(facts["mmio"]) + 1))
    n_pcie = len(pcie_windows(facts))
    pcie = "\n".join(
        f"  MAP_DEVICE_RANGE (APPLE_PCIE_MMIO_RANGE_{i}_BASE, APPLE_PCIE_MMIO_RANGE_{i}_SIZE);"
        for i in range(1, n_pcie + 1))
    if not pcie:
        pcie = ("  //\n"
                "  // No PCIe root complex is described for this family; see the\n"
                "  // memory map header.\n"
                "  //")

    import re
    text, n = re.subn(
        r"(#undef MAP_DEVICE_RANGE)",
        lambda m: m.group(1),
        text)
    # Replace everything between the macro definition and its #undef.
    begin = text.index("} while (FALSE)") + len("} while (FALSE)")
    end = text.index("#undef MAP_DEVICE_RANGE")
    text = text[:begin] + f"""

  //
  // Core system MMIO, generated from the device tree. See the memory map
  // header for how the windows were chosen.
  //
{core}

  //
  // PCIe: config space, then the BAR windows decoded from `ranges`. Without
  // these, enumerating the bus and placing a BAR would fault.
  //
{pcie}

""" + text[end:]
    #
    # The descriptor array is a fixed allocation and the template's bound was
    # written for the template's window count. It has to move with the list
    # generated above, or a family with more windows writes past the end of it.
    #
    n_core = len(facts["mmio"])
    needed = n_core + n_pcie + 3          # + DRAM + framebuffer + terminator
    text, subs = re.subn(
        r"//\n// \w+ uses \d+ core MMIO ranges.*?\n//\n"
        r"#define MAX_VIRTUAL_MEMORY_MAP_DESCRIPTORS \d+",
        "//\n"
        f"// {socs[0].upper()} uses {n_core} core MMIO range(s) + {n_pcie} PCIe range(s) + DRAM +\n"
        f"// framebuffer + terminator = {needed} descriptors, plus headroom.\n"
        "// Generated alongside the window list above -- keep the two in step.\n"
        "//\n"
        f"#define MAX_VIRTUAL_MEMORY_MAP_DESCRIPTORS {needed + 4}",
        text, count=1, flags=re.S)
    if subs != 1:
        raise SystemExit(
            "add-soc: could not retarget MAX_VIRTUAL_MEMORY_MAP_DESCRIPTORS in "
            f"{template}FamilyPkg's memory-init library. Refusing to emit one "
            "whose descriptor bound was sized for a different SoC.")
    mem.write_text(text, encoding="utf-8")


def generate(name, dtb, socs, template, machines, cpu_ssdt=True, boot_uid=0,
             caveats=""):
    facts = socfacts.facts(dtb)
    dst = SILICON / f"{name}FamilyPkg"
    if dst.exists():
        shutil.rmtree(dst)
    (dst / "AcpiTables").mkdir(parents=True)
    (dst / "Include/Library").mkdir(parents=True)

    p = topology_prefix(name, socs)
    (dst / f"{name}FamilyPkg.dec").write_text(gen_dec(name, facts, socs))
    (dst / f"{name}FamilyPkg.dsc.inc").write_text(gen_dsc_inc(name, facts, socs))
    (dst / f"Include/Library/{name}FamilyVirtualMemoryMapDefines.h").write_text(
        gen_memmap_header(name, facts, socs))
    (dst / f"AcpiTables/{p}Topology.h").write_text(
        gen_topology_header(name, facts, socs, boot_uid))
    if cpu_ssdt:
        (dst / "AcpiTables/Cpus.asl").write_text(gen_cpus_asi(name, facts, socs))
    (dst / "AcpiTables/MADT_Static.aslc").write_text(gen_madt(name, facts, socs, boot_uid))
    (dst / "AcpiTables/PPTT.aslc").write_text(gen_pptt(name, facts, socs))
    (dst / "AcpiTables/CSRT.aslc").write_text(gen_csrt(name, facts, socs))
    (dst / "AcpiTables/CPUAcpiTables.inf").write_text(
        gen_cpu_acpi_inf(name, facts, socs, cpu_ssdt))
    (dst / "Readme.md").write_text(gen_readme(name, facts, socs, machines, caveats))

    copy_from_template(name, template, facts, socs)
    return dst, facts


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("name", nargs="?", help="family package name, e.g. T811X")
    ap.add_argument("--dtb", type=Path, help="representative machine's compiled tree")
    ap.add_argument("--socs", help="comma-separated SoC ids this package covers")
    ap.add_argument("--template", default="T8142",
                    help="proven family to copy the shared libraries from")
    ap.add_argument("--machines", default="", help="comma-separated machines, for the Readme")
    ap.add_argument("--caveats", type=Path,
                    help="markdown appended to the generated Readme, for hazards "
                         "of this silicon that firmware cannot work around")
    ap.add_argument("--boot-cpu-uid", type=int, default=0,
                    help="ACPI UID of the core firmware boots on. Its GICC must "
                         "be the MADT's first entry. Default 0; T8142 and T8140 "
                         "come up on a P-core.")
    ap.add_argument("--no-cpu-ssdt", action="store_true",
                    help="do not emit the processor-container SSDT. Needed when a "
                         "board this family serves declares processors in its own "
                         "DSDT, because two declarations of \\_SB.DIE0 collide.")
    ap.add_argument("--list", action="store_true", help="list existing family packages")
    args = ap.parse_args()

    if args.list:
        for d in sorted(SILICON.glob("*FamilyPkg")):
            n = len(list(d.rglob("*")))
            print(f"{d.name:22} {n:3} files")
        return 0

    if not (args.name and args.dtb and args.socs):
        ap.error("name, --dtb and --socs are required")

    socs = args.socs.split(",")
    machines = [m for m in args.machines.split(",") if m]
    dst, facts = generate(args.name, args.dtb, socs, args.template, machines,
                          cpu_ssdt=not args.no_cpu_ssdt, boot_uid=args.boot_cpu_uid,
                          caveats=args.caveats.read_text() if args.caveats else "")
    c = facts["cpu"]
    print(f"{args.name}FamilyPkg -> {dst.relative_to(REPO)}")
    print(f"  {facts['model']}")
    print(f"  {c['cpu_count']} cores / {len(c['clusters'])} clusters, "
          f"{len(facts['mmio'])} MMIO windows, {len(facts['pcie'])} PCIe RC")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
