/** @file
  CPU topology for the Apple T8112 family.

  Generated by Tools/add-soc.py from the device tree for
  Apple MacBook Air (13-inch, M2, 2022).

  Covers: t8112

  UNVERIFIED. Every address, core count and window below is what the device
  tree states; none of it has been read off this silicon by us, and no machine
  in this family has been booted. Treat a successful build as evidence that the
  package is self-consistent and nothing more.

  THE CORE COUNT IS THE DIE, NOT THE MACHINE

  Apple bins these parts. The device tree describes the die as fabricated, and a
  given machine may have fewer cores fused on -- an M2 Pro die carries 12 and
  ships as 10 or 12, an M4 die carries 10 and ships as 8 or 10. Publishing a
  GICC for a core that is not there is not harmless: Windows issues PSCI CPU_ON
  for every enabled entry, and a truthful failure is answered with SYSTEM_RESET.

  AcpiPlatformDxe trims the MADT to the CPUs the live ADT reports before
  installing it, which is what makes a die-sized table safe here. The counts
  below are the ceiling that sizes the table.

  EFFICIENCY CLASS

  ACPI 6.3 defines a LOWER Processor Power Efficiency Class as MORE efficient,
  so E-cores are 0 and P-cores 1. That is what T6020J414sTopology.h does and
  what is emitted here. T8142J813Topology.h emits the opposite and documents
  why; do not copy it.

  SPDX-License-Identifier: BSD-2-Clause-Patent OR MIT
**/

#ifndef T8112_TOPOLOGY_H_
#define T8112_TOPOLOGY_H_

#define T8112_CPU_COUNT        8
#define T8112_CLUSTER_COUNT    2

#define T8112_CLUSTER0_CORE_COUNT    4   // E-cores
#define T8112_CLUSTER0_UID_BASE      0
#define T8112_CLUSTER0_L2_SIZE    0x00400000
#define T8112_CLUSTER0_EFFICIENCY    0

#define T8112_CLUSTER1_CORE_COUNT    4   // P-cores
#define T8112_CLUSTER1_UID_BASE      4
#define T8112_CLUSTER1_L2_SIZE    0x01000000
#define T8112_CLUSTER1_EFFICIENCY    1
//
// The core the firmware boots on must be the MADT's first GICC entry
// (ACPI 6.3 section 5.2.12.14). UID 0 is correct for every SoC we have
// measured except T8142, where m1n1 comes up on a P-core. UNVERIFIED here.
//
#define T8112_BOOT_CPU_UID 0

//
// Architected timer GSIVs, kept in step with T811XFamilyPkg.dsc.inc. Arbitrary:
// the timers are per-CPU FIQs on this silicon, not GIC PPIs.
//
#define T8112_GTDT_SECURE_EL1_GSIV    19
#define T8112_GTDT_NONSECURE_EL1_GSIV 17
#define T8112_GTDT_VIRTUAL_EL1_GSIV   18
#define T8112_GTDT_NONSECURE_EL2_GSIV 20

//
// Interrupt controller base, from the device tree. The geometry that goes with
// it -- IRQ counts, register strides, capability offsets -- is NOT in any
// device tree; Linux and m1n1 both read it off the controller at runtime. See
// CSRT.aslc.
//
#define T8112_AIC_BASE 0x000000023B0C0000ULL
#define T8112_AIC_SIZE 0x0000000000008000ULL

#endif /* T8112_TOPOLOGY_H_ */
